### ISSUE TITLE
The code for obtaining nrrd files.

### ISSUE THREAD

**Issue by Fatima-Ito** [MIAinCS/TiCNet#2]
Thank you very much for the great job.

When I tried to run your code, I got an error:

FileNotFoundError: [Errno 2] No such file or directory: 'Luna16/preprocessed/1.3.6.1.4.1.14519.5.2.1.6279.6001.994459772950022352718462251777_seg.nrrd'
which related with the code:
  File "/media/Jack/jsdushjdus/Experiments/Segmentation/TiCnet/dataset/bbox_reader.py", line 70, in __getitem__
    imgs = self.load_img(filename)

I successfully ran the code of "preprocess.py" and "cvrt_annos_to_npy.py", but I cannot find any "xxxxxx_seg.nrrd", could you please provide the code for generating the nrrd files?

**Comment by imelolee** [comment]
Please change the file suffix to the file type you saved
